# Generated by Django 4.2 on 2023-09-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Sex',
            field=models.CharField(default='Male', max_length=150),
            preserve_default=False,
        ),
    ]
