# Generated by Django 4.2 on 2023-09-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_stage', '0002_person_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
